NewsPortal/News/urls.py
from django.urls import path

from .views import (
    NewsList,
    NewsDetail,
    NewsSearch,
    NewsCreate,
    NewsEdit,
    NewsDelete,
    ArticleCreate,
    EditProfile,
    ProfileDetail,
    make_author,
    subscribe_to_news_category
)
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('profile/', ProfileDetail.as_view(), name='profile'),
    path('profile/edit/', EditProfile.as_view(), name='profile_edit'),
    path('profile/upgrade/', make_author, name='make_author'),
    path('search/', NewsSearch.as_view(), name='news_search'),
    path('news/<int:post_id>/subscribe', subscribe_to_news_category, name='news_subscribe'),
    path('article/create/', ArticleCreate.as_view(), name='article_create'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('news/<int:pk>/edit/', NewsEdit.as_view(), name='news_update'),
    path('news/<int:id>/', NewsDetail.as_view(), name='news_detail'),
    path('', NewsList.as_view(), name='news_list'),
]

NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import routers

from News import views

# router = routers.DefaultRouter()
# router.register(r'author', views.AuthorViewSet)
# router.register(r'post', views.PostViewSet)
# router.register(r'comment', views.CommentViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include(router.urls)),
    # path('api-auth/', include('rest_frameworks.urls', namespace='rest_framework')),
    path('i18n/', include('django.conf.urls.i18n')), # подключаем встроенные эндопинты для работы с локализацией
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('api/v1/', include('apis.urls')),
    path('', include('News.urls')),
]

NewsPortal/News/models.py
# Create your models here.
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum
from django.core.cache import cache
from django.urls import reverse


class User(AbstractUser):
    '''Модель юзера наследуемая от AbstractUser'''

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self) -> str:
        '''Получение абсолютного адреса профиля юзера'''
        return reverse('profile')

    class Meta:
        '''Добавлене названия таблиц в админке'''
        verbose_name = pgettext_lazy('text for verbose_name of User admin', 'User')
        verbose_name_plural = pgettext_lazy('text for verbose_name of User admin', 'Users')


class Author(models.Model):
    '''Модель автора поста/новости на сайте'''
    user = models.OneToOneField(to=User,
                                on_delete=models.CASCADE,
                                related_name='author',
                                verbose_name=pgettext_lazy('help text for Author model', 'User name'),
                                help_text=_('choose user name from list'))
    user_rating = models.SmallIntegerField(default=0,
                                           db_column='rating',
                                           verbose_name=pgettext_lazy('help text for Author model', 'User rating'),
                                           help_text=_('enter user rating'))

    def __str__(self) -> None:
        '''Возвращает полное имя юзера на сайте (имя, фамилия)'''
        return User.get_full_name(self.user)

    class Meta:
        '''Добавлене названия таблиц в админке'''
        verbose_name = pgettext_lazy('help text for verbose_name of Author admin', 'Author'),
        verbose_name_plural = pgettext_lazy('help text for verbose_name of Author admin', 'Authors')

    @staticmethod
    def update_rating(user) -> None:
        '''
        Обновляет и сохраняет рейтинг автора на сайте.
        Общий рейтинг считается исходя из рейтинга постов автра,
        рейтинга комментариев юзера и рейтига комментариев под постом автора.
         '''
        rating_posts_user = rating_comments_user = rating_comments_on_post_user = 0

        if user.author.posts.all().exists():
            rating_posts_user = user.author.posts.aggregate(rating=Sum('_post_rating'))['rating']

        if user.comments.all().exists():
            rating_comments_user = user.comments.aggregate(rating=Sum('_comment_rating'))['rating']

        if user.author.posts.all().exists():
            for post in user.author.posts.all():
                rating_comments_on_post_user += post.comments.aggregate(
                    rating=Sum('_comment_rating'))['rating']

        user.author.user_rating = rating_posts_user * 3 \
                                  + rating_comments_user \
                                  + rating_comments_on_post_user
        user.author.save()


class Category(models.Model):
    '''Модель описывает категории статьей на сайте и их подписчиков (юзеров)'''
    category_name = models.CharField(max_length=64,
                                     unique=True,
                                     db_column='name',
                                     verbose_name=pgettext_lazy('help text for Category model', 'Category name'),
                                     help_text=_('input category name'))
    subscribers = models.ManyToManyField(to='User',
                                         through='CategorySubcribes',
                                         db_column='category', )

    def __str__(self):
        '''Возвращает заголок поста/новости'''
        return f'{self.category_name.title()}'

    class Meta:
        '''
        Добавление названия таблиц в админке и
        сортировка категорий по имени.
        '''
        verbose_name = pgettext_lazy('help text for verbose_name of Category admin', 'Category'),
        verbose_name_plural = pgettext_lazy('help text for verbose_name of Category admin', 'Categories')
        ordering = ['category_name']

    @property
    def number_of_subscribers(self):
        return self.subscribers.count()


class Post(models.Model):
    '''Модель описывает посто на сайет (новость или статья)'''
    news = 'NE'
    article = 'AR'
    TYPE_ITEM = [
        (news, 'Новости'),
        (article, 'Статья')
    ]

    author = models.ForeignKey(to='Author',
                               on_delete=models.CASCADE,
                               db_column='author',
                               related_name='posts',
                               verbose_name=pgettext_lazy('help text for Author model', 'Author', ),
                               help_text=_('choose author'))
    type = models.CharField(max_length=2,
                            choices=TYPE_ITEM,
                            default=news,
                            verbose_name=pgettext_lazy('help text for Author model', 'Type'),
                            help_text=_('choose type post')
                            )
    date = models.DateField(auto_now_add=True,
                            db_column='date',
                            verbose_name=pgettext_lazy('help text for Author model', 'Date'),
                            help_text=_('enter date post'))
    category = models.ManyToManyField(to='Category',
                                      through='PostCategory',
                                      db_column='category', )
    title = models.CharField(default='',
                             max_length=128,
                             db_column='header',
                             verbose_name=pgettext_lazy('help text for Author model', 'Title'),
                             help_text=_('enter title of post'))
    text = models.TextField(db_column='text',
                            verbose_name=pgettext_lazy('help text for Author model', 'Text'),
                            help_text=_('enter text'))
    _post_rating = models.SmallIntegerField(default=0,
                                            db_column='rating',
                                            verbose_name=pgettext_lazy('help text for Author model', 'Rating'),
                                            help_text=_('enter rating of post'), )

    class Meta:
        '''
        Добавление названия таблиц в админке и
        сортировка постов по дате добавленя.
        '''
        verbose_name = pgettext_lazy('help text for verbose_name of Post admin', 'Post'),
        verbose_name_plural = pgettext_lazy('help text for verbose_name of Post admin', 'Posts')
        ordering = ['date']

    def __str__(self) -> str:
        '''Выводит автора статьи и первые 100 знаков статьи'''
        return f'{self.author}: {self.text[:100]}'

    @property
    def post_rating(self):
        '''Получение рейтинга поста'''
        return self._post_rating

    @post_rating.setter
    def post_rating(self, value):
        self._post_rating = value
        self.save()

    def like(self) -> None:
        '''Увеличивает рейтинг статьи на 1'''
        self.post_rating += 1
        self.save()

    def dislike(self):
        '''Уменьшает рейтинг статьи на 1'''
        self.post_rating -= 1
        self.save()

    def preview(self):
        '''Выводит превью статьи, первые 123 знака'''
        return f'{self.text[:123]} ...'

    def get_absolute_url(self) -> str:
        '''Получене абсолютной ссылки на кокрентую статью'''

        return reverse('news_detail', kwargs={'id': self.id})

    def save(self, *args, **kwargs):
        '''
        Переопределяет стандарнты метод save.
        Удаляет данные статьи из кэша, после ее сохранения/изменения.
        '''
        super().save(*args, **kwargs)
        cache.delete(f'news-{self.id}')


class PostCategory(models.Model):
    '''Промежуточная модель связывающая таблицы Post и Category'''
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE)


class Comment(models.Model):
    '''Модель комментариев поста'''
    post = models.ForeignKey(to='Post',
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name=pgettext_lazy('help text for Comment models', 'Post'),
                             help_text=_('choose post'))
    user = models.ForeignKey(to='User',
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name=pgettext_lazy('help text for Comment models', 'User'),
                             help_text=_('choose user'))
    comment_text = models.TextField(db_column='text',
                                    verbose_name=pgettext_lazy('help text for Comment models', 'Comment on post'),
                                    help_text=_('enter comment on post'))
    comment_date = models.DateTimeField(auto_now_add=True,
                                        db_column='date', )
    _comment_rating = models.IntegerField(default=0,
                                          db_column='rating',
                                          verbose_name=pgettext_lazy('help text for Comment models', 'Comment rating'),
                                          help_text=_('Enter comment rating'))

    class Meta:
        '''
        Добавление названия таблиц в админке и
        сортировка постов по дате добавленя.
        '''
        verbose_name = pgettext_lazy('help text for verbose_name of Comment admin', 'Comment'),
        verbose_name_plural = pgettext_lazy('help text for verbose_name of Comment admin', 'Comments')

    def __str__(self):
        return self.comment_text

    @property
    def comment_rating(self):
        '''Получение рейтинга комментария'''
        return self._comment_rating

NewsPortal/News/forms.py
from django.core.exceptions import ValidationError
from django.forms import Textarea, SelectMultiple
from django.contrib.auth.models import Group
from allauth.account.forms import SignupForm
from django import forms
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy

from .models import (
    Post,
    Category,
    Author,
    User,
    Comment,
)


class PostForm(forms.ModelForm):
    '''Форма поста(новости)'''
    author = forms.ModelChoiceField(queryset=Author.objects.all(),
                                    label=_('Author of post'),
                                    empty_label=_('-- choose author --'), )
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),
                                              label=_('Category of post'),
                                              widget=SelectMultiple(attrs={'multiple': True}))
    title = forms.CharField(min_length=15, max_length=150, label=_('Title of post'))
    text = forms.CharField(widget=Textarea(attrs={'cols': 80, 'rows': 10}),
                           label=pgettext_lazy('text for PostForm', 'Text'),
                           min_length=100)

    class Meta:
        model = Post
        fields = [
            'author',
            'category',
            'title',
            'text',
        ]

    def clean(self):
        '''Валидация формы: текст поста не должен совпадать с заголовком'''
        clean_data = super().clean()
        title = clean_data.get('title')
        text = clean_data.get('text')
        if title == text:
            raise ValidationError('Текст поста не должен быть идентичен заголовку.')
        return clean_data


class ArticleForm(forms.ModelForm):
    '''Форма поста(статьи)'''
    author = forms.ModelChoiceField(queryset=Author.objects.all(),
                                    label='Автор поста',
                                    empty_label='-- Выберите автора --', )
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),
                                              label='Категория поста',
                                              widget=SelectMultiple(attrs={'multiple': True}))
    title = forms.CharField(min_length=15, max_length=150, label='Заголовок поста')
    text = forms.CharField(widget=Textarea(attrs={'cols': 80, 'rows': 10}),
                           label='Текст поста',
                           min_length=100)

    class Meta:
        model = Post
        fields = [
            'author',
            'category',
            'title',
            'text',
        ]

    def clean(self):
        '''Валидация формы: текст поста не должен совпадать с заголовком'''
        clean_data = super().clean()
        title = clean_data.get('title')
        text = clean_data.get('text')
        if title == text:
            raise ValidationError('Текст поста не должен быть идетичен заголовку.')
        return clean_data


class ProfileForm(forms.ModelForm):
    '''Форма профиля пользовтеля '''

    class Meta:
        username = forms.CharField(label=_('Username'))
        first_name = forms.CharField(label=_('First name'))
        last_name = forms.CharField(label=_('Last name'))
        email = forms.EmailField(label=_('Email'))

        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]


class BasicSignupForm(SignupForm):

    def save(self, request):
        '''При регистрации нового пользователя он добавляется в группу common'''
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user


class MyCustomSocialSignupForm(SignupForm):
    def save(self, request):
        '''При регистрации нового пользователя он добавляется в группу common'''
        user = super(MyCustomSocialSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text', 'user')

NewsPortal/templates/news/adding_news_newsletter.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Здравствуй, {{ subscribers_name}}. Новая статья в твоём любимом разделе</title>
</head>
<body>
<h2> Здравствуй, {{ subscribers_name }}. Новая статья в твоём любимом разделе</h2>
<p> Вы подписались на новости: {{ categories }}.</p>
<div>
    <p>{{ instance.date|date:'d.m.Y' }}</p>
    <h3><a href="http://127.0.0.1:8000{% url  'news_detail' instance.id %}">{{ instance.title }}</a></h3>
    <p>{{ instance.text|truncatewords:50 }}</p>
</div>
</body>
</html>

NewsPortal/templates/news/news_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block content %}
<h1>{%trans 'Deleting a post' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Delete post?' %} "{{ object.title}}"?</p>
    <button class="btn btn-danger ml-2" type="submit">{% trans 'Confirm' %}</button>
</form>
<br/>
{% endblock content %}

NewsPortal/templates/news/news_detail.html
{% extends 'flatpages/default.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% load i18n %}

{% block title %}
{% trans 'News' %}
{% endblock title %}

{% block content %}
<h3> {{ news.title|censor}}</h3>
<div>
    <p>{{ news.date|date:'d.m.Y'}}</p>
</div>
<div>
    <p>{{ news.text|censor }}</p>
</div>

{% if user.is_authenticated %}
<p>
    {% if perms.News.change_post %}
    <a href="{% url 'news_update' news.pk %}">{% trans 'Edit post' %}</a> |
    {% endif %}
    {% if perms.News.delete_post %}
    <a href="{% url 'news_delete' news.pk %}">{% trans 'Delete news' %}</a>
    {% endif %}
</p>
<p><a href="{% url 'news_subscribe' news.id %}">{% trans 'Subscribe' %}</a></p>
{% endif %}

<p>{% trans 'back to ' %}<a href="{% url 'news_list' %}">{% trans 'all post' %}</a></p>
<h4>{% trans 'Comments' %}</h4>
{% for comment in news.comments.all %}
<p>{{comment.user}} &middot; {{ comment }}</p>
{% endfor %}
<hr>

<h4>{% trans 'Add comment' %}</h4>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">{% trans 'Save' %}</button>
</form>
{% endblock content %}

NewsPortal/templates/news/news_edit.html
{% extends 'flatpages/default.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<hr>
<h1>{% trans 'Post editing' %}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="{% trans 'Save' %}">
</form>
<br/>
{% endblock content %}

NewsPortal/templates/news/news_list.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load i18n %}

{% block title %}{% trans 'News' %}{% endblock title %}

{% block content %}
<h1>{% trans 'All news' %}</h1>
<h3>{% trans 'Total articles' %}: {{ news_list|length }}</h3>
<hr>

{% for news in news_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold"><a href="{{ news.get_absolute_url }}">{{ news.title|censor }}</a></span>&middot;
        <span class="text-muted">{{ news.author }} |
                {{news.date|date:'d.m.Y'}}</span>
    </div>
    <div class="card-body">
        <p>{{ news.text|truncatewords:20|censor }}</p>
        {% if perms.News.change_post %}
        <a href="{% url 'news_update' news.pk %}">{% trans 'Edit' %}</a> |
        {% endif %}
        {% if perms.News.delete_post %}
        <a href="{% url 'news_delete' news.pk %}">{% trans 'Delete' %}</a>
        {% endif %}
    </div>
    <div class="card-footer text-center text-muted">
        {% for comment in news.comments.all %}
        <p>
                <span class="font-weight-bold">
                    {{ comment.user }} &middot;
                </span>
            {{ comment }}
        </p>
        {% endfor %}
    </div>
</div>
<br/>

{% empty %}
<h2>{% trans 'No news' %}</h2>
{% endfor %}

<div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">&laquo; {% trans 'back' %}</a>
                <a href="?page=1">1</a>
                {% if page_obj.previous_page_number != 1 %}
                    ...
                    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                {% endif %}
            {% endif %}

            <span class="current">
                 {% if paginator.num_pages > 1 %}
                    <strong>{{ page_obj.number }}</strong>
                {% endif %}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?page={{page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %} &raquo;</a>
            {% endif %}
        </span>
</div>
{% endblock content %}

NewsPortal/templates/news/news_new.html
{% extends 'flatpages/default.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Adding a new post ' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="{% trans 'Save' %}">
</form>
<br/>
{% endblock content %}

NewsPortal/templates/news/news_search.html
{% extends 'flatpages/default.html' %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Search for articles on the site' %}</h1>
<form action="" method="GET">
    {{ filterset.form|crispy }}
   <button type="submit" class="btn btn-primary">{% trans 'Find' %}</button>
</form>
<hr>

{% for news in news_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold"><a href="{{ news.get_absolute_url }}">{{ news.title|censor }}</a></span>&middot;
        <span class="text-muted">{{ news.author }} |
                {{news.date|date:'d.m.Y'}}</span>
    </div>
    <div class="card-body">
        <p>{{ news.text|truncatewords:20|censor }}</p>
        {% if perms.News.change_post %}
        <a href="{% url 'news_update' news.pk %}">{% trans 'Edit' %}</a> |
        {% endif %}
        {% if perms.News.delete_post %}
        <a href="{% url 'news_delete' news.pk %}">{% trans 'Delete' %}</a>
        {% endif %}
    </div>
</div>
<br/>
{% empty %}
<h2>{% trans 'No news' %}</h2>
{% endfor %}

<div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">&laquo; {% trans 'back' %}</a>
                        <a href="?page=1">1</a>
                        {% if page_obj.previous_page_number != 1 %}
                            ...
                            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                        {% endif %}
                    {% endif %}

                    <span class="current">
                         {% if paginator.num_pages > 1 %}
                            {{ page_obj.number }}
                        {% endif %}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        {% if paginator.num_pages != page_obj.next_page_number %}
                        ...
                        <a href="?page={{page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a>
                        {% endif %}
                        <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %} &raquo;</a>
                    {% endif %}
                </span>
</div>
{% endblock %}

NewsPortal/templates/news/profile.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}
{% trans 'User Profile' %}
{% endblock title %}

{% block content %}
<h3> {{ profile.username}}</h3>
<div>
    <table>
        <tr>
            <td>{% trans 'First name' %}:</td>
            <td>{{ profile.first_name }}</td>
        </tr>
        <tr>
            <td>{% trans 'Last name' %}:</td>
            <td>{{ profile.last_name }}</td>
        </tr>
        <tr>
            <td>{% trans 'Email' %}:</td>
            <td>{{ profile.email }}</td>
        </tr>
    </table>
    {% if is_not_author %}
        <button><a class="btn btn-primary ml-2" href="/profile/upgrade">{% trans 'Become an author'%}</a></button>
    {% endif %}
    <a class="btn btn-primary ml-2" href="/profile/edit">{% trans 'Profile edit' %}</a>
    <a class="btn btn-primary ml-2" href="/accounts/logout">{% trans 'Log out' %}</a>
</div>
{% endblock content %}

NewsPortal/templates/news/profile_edit.html
{% extends 'flatpages/default.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Edit user profile' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="{% trans 'Save' %}">
</form>
{% endblock content %}

NewsPortal/templates/news/subcribe.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Подписка
{% endblock title %}

{% block content %}
<h3> Уважаемый, {{ user }}!</h3>
<p>Подписка на следующие категории успешно оформлена:</p>
{% for category in categories_subscribed %}
<ul>
    <li>{{category.category_name|title}}</li>
</ul>
{% endfor %}
<div>
    <button><a href="{% url 'news_list'  %}">К списку новостей</a></button>
</div>
{% endblock content %}

NewsPortal/templates/news/weekly_newsletter_to_subscribers.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Здравствуй, {{ user }}. Новые статьи в твоих любимых разделах за неделю</title>
</head>
<body>
<h2> Здравствуй, {{ user }}. Новые статьи в твоих любимых разделах за неделю: </h2>
<ul>
    {% for post in list_of_post %}
    <li>
        <p>{{ post.date|date:'d.m.Y' }}</p>
        <h3><a href="http://127.0.0.1:8000{% url  'news_detail' post.id %}">{{ post.title }}</a></h3>
        <p>{{ post.text|truncatewords:25 }}</p>
    </li>
    {% endfor %}
</ul>
</body>
</html>